### ISSUE TITLE
Help in get Path

### ISSUE THREAD

**Issue by UmairAhmed420** [1552980358/MusicPlayer#2]
Hello Sir, as you know MediaStore Data is Deprecated.... so i m looking just to get a path of audio Files so i can play it ..... can you provide me method of that so i can get path of those audio Files which i select from my view Thanks

**Comment by KShChan** [comment]
You don't need to get the absolute path of audio files, instead, just get the media id with android database. Refer to [AudioImportActivity.kt](https://github.com/1552980358/MusicPlayer/blob/dev/app/src/main/java/app/github1552980358/android/musicplayer/activity/AudioImportActivity.kt) line 117.
`contentResolver.query()` is the calling of getting all music data in your device. Use `getString(getColumnIndex(MediaStore.Audio.AudioColumns._ID))` of the query to fetch the media id of each audio files. You can play audio with MediaPlayer by calling `MediaPlayer.setDataSource()` with the url link, which the link is the phrasing of the media id fetch above with method `Uri.parse(MediaStore.Audio.Media.EXTERNAL_CONTENT_URI.toString() + File.separator + mediaId)`. Look at [MediaPlayerUtil.kt](https://github.com/1552980358/MusicPlayer/blob/dev/app/src/main/java/app/github1552980358/android/musicplayer/service/MediaPlayerUtil.kt), line 67
